esphome:
  name: rts-buzzer

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rts-Buzzer Fallback Hotspot"
    password: ""

captive_portal:

mqtt:
  broker: "192.168.4.143" # Replace with the IP address of your Home Assistant server, if necessary
  username: "homeassistant" # Optional, if authentication is enabled
  password: "" # Optional, if authentication is enabled
  discovery: True # Optional, allows Home Assistant to auto-discover your device
  on_message:
    - topic: "esp32/rts-buzzer"
      payload: "ON"
      then:
        - output.turn_on: buzzer
    - topic: "esp32/rts-buzzer"
      payload: "OFF"
      then:
        - output.turn_off: buzzer

output:
  - platform: gpio
    pin: GPIO23 # Change to the GPIO pin where your buzzer is connected
    id: buzzer
    inverted: false

# Define a switch to control the buzzer using MQTT
switch:
  - platform: template
    name: "Doorbell Buzzer"
    turn_on_action:
      - output.turn_on: buzzer
    turn_off_action:
      - output.turn_off: buzzer
